### ISSUE TITLE
Not compatible with :bolt_sips 2.0.11+

### ISSUE THREAD

**Issue by Awlexus** [dominique-vassard/seraph#15]
The newest version of `:bolt_sips` introduced a [new feature]( https://github.com/florinpatrascu/bolt_sips/commit/2471f35862b6031bb14626c941f3bc04b1949066#diff-3633d555cc7acc83adb2d76cfcebdc41acb12fa205345eeb43aae24652f51584R147-R153) which broke compatibility with seraph. 

I'm not too familiar with this seraph, but I think this could be fixed by always adding the prefix as an option when performing an query or updating :bolt_sips to have a sensible default value for the timeout.

**Comment by dominique-vassard** [comment]
Hello,

you're right when you say:
> this could be fixed by always adding the prefix as an option when performing an query

In fact, I've got this fix in progress as I was working on implementing `timestamps()` but work and other things make me forget about this.
I'll try to find some time this week-end to published the fixed version (and perhaps timestamps too)

**Comment by dominique-vassard** [comment]
Fixed and published!
